"""Build exam-vocab workbook: 수능/토익/공무원/내신 × (단어100 + 숙어50)."""
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ============================================================
# DATA
# ============================================================

수능_단어 = [
    ("abandon", "버리다, 포기하다", "He had to abandon his car in the snowstorm."),
    ("abstract", "추상적인", "Beauty is an abstract concept that varies by culture."),
    ("accumulate", "축적하다", "Dust tends to accumulate on bookshelves."),
    ("acknowledge", "인정하다", "She acknowledged her mistake and apologized."),
    ("adapt", "적응시키다", "Animals must adapt to their environment to survive."),
    ("adequate", "충분한, 적절한", "The room is adequate for ten people."),
    ("adopt", "채택하다, 입양하다", "The committee adopted a new policy."),
    ("advocate", "옹호하다", "She advocates for children's rights."),
    ("ambiguous", "모호한", "His answer was ambiguous and confusing."),
    ("analyze", "분석하다", "Scientists analyze data to draw conclusions."),
    ("anticipate", "예상하다", "We anticipate strong sales next quarter."),
    ("apparent", "분명한", "It was apparent that he was tired."),
    ("appropriate", "적절한", "Please wear appropriate clothing for the interview."),
    ("arbitrary", "임의적인", "The decision seemed arbitrary and unfair."),
    ("articulate", "명확히 표현하다", "She articulated her thoughts clearly."),
    ("assert", "주장하다", "He asserted that he was innocent."),
    ("assume", "가정하다", "Don't assume people know what you mean."),
    ("attain", "달성하다", "She attained her goal of becoming a doctor."),
    ("attribute", "~의 탓으로 돌리다", "He attributes his success to hard work."),
    ("authentic", "진짜의", "This is an authentic Italian recipe."),
    ("awareness", "인식", "Public awareness of climate change is growing."),
    ("behalf", "대신, 편", "I am speaking on behalf of my team."),
    ("beneficial", "유익한", "Exercise is beneficial to health."),
    ("bias", "편견", "The article showed a clear bias."),
    ("capacity", "능력, 수용력", "The stadium has a capacity of 50,000."),
    ("challenge", "도전하다", "She challenged him to a debate."),
    ("circumstance", "상황", "Under no circumstances should you open this door."),
    ("coherent", "일관성 있는", "Please write a coherent argument."),
    ("collaborate", "협력하다", "The two scientists collaborated on the project."),
    ("compel", "강요하다", "The evidence compelled him to confess."),
    ("complement", "보완하다", "The wine complements the meal nicely."),
    ("comprehensive", "포괄적인", "The report is comprehensive and detailed."),
    ("conceive", "생각해내다", "He conceived a brilliant plan."),
    ("conform", "따르다, 순응하다", "Students must conform to school rules."),
    ("consequence", "결과", "Every action has consequences."),
    ("constitute", "구성하다", "Women constitute 60% of the workforce."),
    ("contemplate", "숙고하다", "She contemplated her future career."),
    ("contradict", "모순되다", "His actions contradict his words."),
    ("contribute", "기여하다", "Many factors contribute to success."),
    ("controversy", "논란", "The decision caused great controversy."),
    ("convert", "전환하다", "We converted the garage into an office."),
    ("convey", "전달하다", "Words cannot convey my gratitude."),
    ("crucial", "결정적인", "Sleep is crucial for good health."),
    ("cultivate", "경작하다, 양성하다", "Farmers cultivate the land each spring."),
    ("deduce", "추론하다", "Sherlock deduced the truth from small clues."),
    ("dedicate", "헌신하다", "She dedicated her life to teaching."),
    ("deficient", "부족한", "His diet is deficient in vitamins."),
    ("demonstrate", "입증하다", "The experiment demonstrates the theory."),
    ("derive", "유래하다", "Many English words derive from Latin."),
    ("designate", "지정하다", "This area is designated for parking."),
    ("deteriorate", "악화되다", "His health began to deteriorate rapidly."),
    ("devote", "바치다", "He devotes his weekends to family."),
    ("diminish", "줄어들다", "The pain gradually diminished."),
    ("discern", "식별하다", "It's hard to discern the truth here."),
    ("disclose", "공개하다", "He refused to disclose his sources."),
    ("distinguish", "구별하다", "It's hard to distinguish the twins."),
    ("distort", "왜곡하다", "The media distorted the facts."),
    ("diverse", "다양한", "New York is a diverse city."),
    ("dominate", "지배하다", "The team dominated the match."),
    ("elaborate", "정교한; 자세히 설명하다", "Could you elaborate on that point?"),
    ("elicit", "이끌어내다", "The teacher tried to elicit answers from students."),
    ("eliminate", "제거하다", "We must eliminate waste from the process."),
    ("embrace", "받아들이다", "We should embrace new technology."),
    ("emphasize", "강조하다", "He emphasized the importance of honesty."),
    ("encounter", "마주치다", "I encountered an old friend at the store."),
    ("endorse", "지지하다", "The mayor endorsed the new policy."),
    ("enhance", "향상시키다", "Music can enhance your mood."),
    ("enroll", "등록하다", "She enrolled in a Spanish course."),
    ("equivalent", "동등한", "One dollar is equivalent to about 1,300 won."),
    ("essential", "필수적인", "Water is essential for life."),
    ("evaluate", "평가하다", "Teachers evaluate students' performance."),
    ("evident", "명백한", "It was evident he was lying."),
    ("evoke", "불러일으키다", "The song evokes childhood memories."),
    ("exaggerate", "과장하다", "Don't exaggerate the problem."),
    ("exceed", "초과하다", "Sales exceeded our expectations."),
    ("exclude", "제외하다", "The price excludes tax."),
    ("exhibit", "전시하다", "The museum exhibits ancient art."),
    ("exploit", "착취하다, 이용하다", "Companies should not exploit workers."),
    ("external", "외부의", "External factors affect our business."),
    ("fascinate", "매혹하다", "Space fascinates many children."),
    ("feasible", "실현 가능한", "The plan is feasible with more funding."),
    ("flourish", "번창하다", "The business flourished last year."),
    ("fluctuate", "변동하다", "Prices fluctuate daily."),
    ("foster", "육성하다", "We must foster creativity in schools."),
    ("fundamental", "근본적인", "Honesty is a fundamental value."),
    ("genuine", "진실한", "Her smile was genuine."),
    ("grasp", "이해하다", "It's hard to grasp this concept."),
    ("hierarchy", "위계", "There is a strict hierarchy in the company."),
    ("hinder", "방해하다", "Bad weather hindered our progress."),
    ("hypothesis", "가설", "Scientists test their hypothesis with experiments."),
    ("illuminate", "밝히다", "The data illuminates the trend."),
    ("imply", "암시하다", "Silence does not imply consent."),
    ("inevitable", "피할 수 없는", "Change is inevitable in life."),
    ("infer", "추론하다", "We can infer the meaning from context."),
    ("inherent", "내재된", "Risk is inherent in any investment."),
    ("innovate", "혁신하다", "Companies must innovate to survive."),
    ("integrate", "통합하다", "We integrate technology into classrooms."),
    ("interpret", "해석하다", "How do you interpret this poem?"),
    ("intuition", "직감", "Trust your intuition sometimes."),
    ("justify", "정당화하다", "The end does not justify the means."),
]

수능_숙어 = [
    ("account for", "설명하다, 차지하다", "How do you account for the missing money?"),
    ("break down", "고장 나다, 분해되다", "The car broke down on the highway."),
    ("bring about", "야기하다", "Technology brought about huge changes."),
    ("carry out", "수행하다", "Scientists carried out the experiment."),
    ("come across", "우연히 만나다", "I came across an old letter."),
    ("come up with", "떠올리다", "She came up with a brilliant idea."),
    ("cope with", "대처하다", "It's hard to cope with stress."),
    ("count on", "의지하다", "You can count on me anytime."),
    ("deal with", "다루다", "Managers deal with conflicts daily."),
    ("depend on", "의존하다", "Children depend on their parents."),
    ("derive from", "~에서 유래하다", "Many words derive from Greek."),
    ("die out", "멸종하다", "Many species are dying out."),
    ("dispose of", "처분하다", "Please dispose of trash properly."),
    ("draw on", "이용하다", "Writers draw on personal experience."),
    ("engage in", "참여하다", "Students engage in various activities."),
    ("fall behind", "뒤처지다", "Don't fall behind in your studies."),
    ("figure out", "알아내다", "I can't figure out the answer."),
    ("focus on", "집중하다", "Let's focus on the main topic."),
    ("for the sake of", "~을 위해", "We work for the sake of our families."),
    ("get rid of", "없애다", "We need to get rid of clutter."),
    ("give in", "굴복하다", "Don't give in to peer pressure."),
    ("give rise to", "야기하다", "Poverty gives rise to crime."),
    ("hand in", "제출하다", "Please hand in your homework."),
    ("in addition to", "~외에도", "In addition to English, she speaks French."),
    ("in spite of", "~에도 불구하고", "In spite of the rain, we went out."),
    ("in terms of", "~의 관점에서", "Think in terms of long-term benefits."),
    ("keep up with", "따라가다", "It's hard to keep up with technology."),
    ("lead to", "초래하다", "Hard work leads to success."),
    ("let down", "실망시키다", "I won't let you down."),
    ("live up to", "부응하다", "He lives up to expectations."),
    ("look into", "조사하다", "Police will look into the matter."),
    ("look up to", "존경하다", "I look up to my grandfather."),
    ("make sense", "말이 되다", "Your explanation makes sense."),
    ("make up for", "보상하다", "I'll make up for my mistake."),
    ("on behalf of", "~을 대신하여", "I speak on behalf of the team."),
    ("owing to", "~때문에", "The game was canceled owing to rain."),
    ("pass away", "돌아가시다", "His grandfather passed away last year."),
    ("pay attention to", "주의를 기울이다", "Pay attention to details."),
    ("put off", "미루다", "Don't put off important tasks."),
    ("put up with", "참다", "I can't put up with this noise."),
    ("refer to", "언급하다", "Please refer to chapter 3."),
    ("result in", "결과를 낳다", "Smoking results in poor health."),
    ("rule out", "배제하다", "We can't rule out that possibility."),
    ("set aside", "한쪽에 두다", "Set aside time for reading."),
    ("show up", "나타나다", "He didn't show up to the meeting."),
    ("stand for", "상징하다", "What does this symbol stand for?"),
    ("take advantage of", "이용하다", "Take advantage of the sale."),
    ("take into account", "고려하다", "Take all factors into account."),
    ("turn out", "판명되다", "It turned out to be a great day."),
    ("up to date", "최신의", "Keep your software up to date."),
]

토익_단어 = [
    ("accommodate", "수용하다", "The hotel can accommodate 200 guests."),
    ("acquire", "인수하다, 획득하다", "The company acquired a smaller competitor."),
    ("agenda", "의제", "The meeting agenda was distributed yesterday."),
    ("allocate", "할당하다", "We allocated $5,000 to marketing."),
    ("amend", "수정하다", "The contract was amended last week."),
    ("appliance", "가전제품", "Kitchen appliances are on sale."),
    ("applicant", "지원자", "We received 50 applicants for the position."),
    ("appraise", "평가하다", "Managers appraise employees annually."),
    ("assemble", "조립하다, 모이다", "Workers assemble cars on the line."),
    ("assignment", "업무, 과제", "I have a new assignment this week."),
    ("attendance", "출석, 참석", "Attendance at the seminar was strong."),
    ("authorize", "권한을 부여하다", "Only managers can authorize refunds."),
    ("beverage", "음료", "Beverages are available at the back."),
    ("boost", "신장시키다", "The ad campaign boosted sales."),
    ("brochure", "안내 책자", "Take a brochure for more information."),
    ("budget", "예산", "We need to stay within budget."),
    ("campaign", "캠페인", "The marketing campaign was successful."),
    ("candidate", "후보자", "Three candidates applied for the position."),
    ("certify", "인증하다", "Our products are certified organic."),
    ("client", "고객", "The client requested a meeting."),
    ("commute", "통근하다", "I commute by subway every day."),
    ("compensate", "보상하다", "We will compensate you for the inconvenience."),
    ("compile", "편집하다, 모으다", "Please compile the data into a report."),
    ("complimentary", "무료의", "Breakfast is complimentary for guests."),
    ("confidential", "기밀의", "This document is confidential."),
    ("confirm", "확인하다", "Please confirm your reservation."),
    ("consultant", "컨설턴트", "We hired a consultant for advice."),
    ("contract", "계약", "We signed a two-year contract."),
    ("corporate", "기업의", "Corporate policy prohibits this."),
    ("coverage", "보장, 보도", "The insurance has full coverage."),
    ("credentials", "자격", "She has impressive credentials."),
    ("decline", "거절하다, 감소하다", "Sales declined last quarter."),
    ("deduct", "공제하다", "Taxes are deducted from your paycheck."),
    ("deliver", "배송하다", "We deliver within 24 hours."),
    ("department", "부서", "Which department do you work in?"),
    ("deposit", "보증금, 예치하다", "A deposit is required."),
    ("distribute", "배포하다", "Please distribute the handouts."),
    ("document", "문서", "Please sign the document."),
    ("draft", "초안", "Please review the draft proposal."),
    ("efficient", "효율적인", "This is a more efficient method."),
    ("eligible", "자격이 있는", "Are you eligible for the discount?"),
    ("employee", "직원", "All employees must wear badges."),
    ("enclose", "동봉하다", "I enclose my resume."),
    ("ensure", "보장하다", "Please ensure all forms are signed."),
    ("envelope", "봉투", "Place the letter in the envelope."),
    ("estimate", "견적", "Please provide a cost estimate."),
    ("exchange", "교환하다", "You can exchange the item within 30 days."),
    ("executive", "임원", "The executive will arrive shortly."),
    ("expand", "확장하다", "The company plans to expand overseas."),
    ("expense", "비용", "Travel expenses will be reimbursed."),
    ("expire", "만료되다", "My passport expires next month."),
    ("facility", "시설", "The facility is open 24 hours."),
    ("feedback", "피드백", "We welcome your feedback."),
    ("finance", "재무", "She works in finance."),
    ("forecast", "예측", "The weather forecast looks good."),
    ("headquarters", "본사", "Our headquarters is in Seoul."),
    ("implement", "실행하다", "We will implement the changes next month."),
    ("inquiry", "문의", "We received an inquiry about the product."),
    ("install", "설치하다", "Technicians will install the system."),
    ("inventory", "재고", "Our inventory is running low."),
    ("invoice", "송장", "Please pay the invoice by Friday."),
    ("itinerary", "여행 일정", "I'll email you the itinerary."),
    ("launch", "출시하다", "We will launch the product in June."),
    ("liability", "책임", "The company has limited liability."),
    ("maintenance", "유지보수", "Equipment requires regular maintenance."),
    ("manufacture", "제조하다", "We manufacture electronics."),
    ("merchandise", "상품", "All merchandise must be returned."),
    ("merger", "합병", "The merger was announced today."),
    ("negotiate", "협상하다", "We need to negotiate the terms."),
    ("notify", "통지하다", "Please notify us of any changes."),
    ("occupy", "차지하다", "We occupy the 5th floor."),
    ("operate", "운영하다", "We operate in 20 countries."),
    ("opportunity", "기회", "This is a great opportunity."),
    ("outstanding", "미지급의, 뛰어난", "The outstanding balance is $500."),
    ("overseas", "해외의", "We have overseas offices."),
    ("patron", "단골 고객", "Loyal patrons receive discounts."),
    ("policy", "정책", "This is our refund policy."),
    ("postpone", "연기하다", "The meeting was postponed."),
    ("premises", "부지, 건물", "Smoking is prohibited on the premises."),
    ("procedure", "절차", "Follow the standard procedure."),
    ("proceed", "진행하다", "Please proceed to gate 5."),
    ("promote", "승진시키다", "She was promoted to manager."),
    ("purchase", "구매", "Thank you for your purchase."),
    ("recruit", "모집하다", "We are recruiting new staff."),
    ("refund", "환불", "We offer a full refund."),
    ("reimburse", "환급하다", "We will reimburse your expenses."),
    ("renovate", "개조하다", "The hotel is being renovated."),
    ("retail", "소매", "She works in retail."),
    ("revenue", "수익", "Annual revenue increased 10%."),
    ("schedule", "일정", "Check the schedule for changes."),
    ("shipment", "발송, 화물", "Your shipment will arrive Tuesday."),
    ("spreadsheet", "스프레드시트", "Update the spreadsheet weekly."),
    ("subscription", "구독", "Cancel your subscription anytime."),
    ("supplier", "공급업체", "We changed suppliers last year."),
    ("survey", "설문조사", "Please complete this survey."),
    ("terminate", "종료하다", "Your contract will terminate next month."),
    ("transaction", "거래", "The transaction was approved."),
    ("vacancy", "공석", "We have a vacancy in HR."),
    ("vendor", "판매업체", "The vendor will deliver tomorrow."),
    ("warehouse", "창고", "Goods are stored in the warehouse."),
]

토익_숙어 = [
    ("account for", "설명하다", "Please account for the missing inventory."),
    ("apply for", "지원하다", "I want to apply for the position."),
    ("as soon as possible", "가능한 빨리", "Please reply as soon as possible."),
    ("ask for", "요청하다", "The customer asked for a refund."),
    ("attend to", "처리하다", "I'll attend to the matter immediately."),
    ("be in charge of", "~을 담당하다", "She is in charge of marketing."),
    ("be subject to", "~의 대상이다", "Prices are subject to change."),
    ("break down", "고장 나다", "The copier broke down again."),
    ("bring up", "언급하다", "Don't bring up that topic."),
    ("call back", "다시 전화하다", "I'll call you back later."),
    ("call off", "취소하다", "The meeting was called off."),
    ("carry out", "실행하다", "We will carry out the plan."),
    ("catch up on", "밀린 일을 처리하다", "I need to catch up on emails."),
    ("check in", "체크인하다", "Please check in at the desk."),
    ("check out", "체크아웃하다", "Check out is at 11 AM."),
    ("come up with", "떠올리다", "We need to come up with a solution."),
    ("cut down on", "줄이다", "We must cut down on costs."),
    ("drop off", "내려주다", "I'll drop off the package."),
    ("fill in for", "대신하다", "Can you fill in for me?"),
    ("fill out", "작성하다", "Please fill out this form."),
    ("follow up", "후속 조치하다", "I will follow up next week."),
    ("get back to", "다시 연락하다", "I'll get back to you soon."),
    ("give a hand", "도와주다", "Could you give me a hand?"),
    ("go over", "검토하다", "Let's go over the report."),
    ("hand in", "제출하다", "Hand in your timesheet by Friday."),
    ("hand out", "나눠주다", "Please hand out these flyers."),
    ("hold on", "잠깐 기다리다", "Hold on, I'll transfer you."),
    ("in advance", "미리", "Pay in advance for a discount."),
    ("in charge of", "담당하는", "Who is in charge of this project?"),
    ("keep track of", "기록을 추적하다", "Keep track of your expenses."),
    ("look forward to", "기대하다", "I look forward to meeting you."),
    ("look into", "조사하다", "We will look into the issue."),
    ("on behalf of", "~을 대신하여", "I write on behalf of my client."),
    ("on schedule", "예정대로", "The flight is on schedule."),
    ("out of stock", "재고가 없는", "That item is out of stock."),
    ("pick up", "픽업하다", "I'll pick you up at 3."),
    ("point out", "지적하다", "Let me point out an error."),
    ("put off", "미루다", "The launch was put off."),
    ("run out of", "다 떨어지다", "We ran out of paper."),
    ("set up", "설치하다, 마련하다", "Set up a meeting tomorrow."),
    ("sign up for", "가입하다", "Sign up for our newsletter."),
    ("stand by", "대기하다", "Please stand by for instructions."),
    ("stock up", "비축하다", "Stock up on office supplies."),
    ("take care of", "처리하다", "I'll take care of the report."),
    ("take over", "인수하다", "She will take over the project."),
    ("take place", "일어나다", "The event takes place Friday."),
    ("turn down", "거절하다", "They turned down our offer."),
    ("turn in", "제출하다", "Turn in the form by 5 PM."),
    ("work out", "운동하다, 해결되다", "Things will work out."),
    ("wrap up", "마무리하다", "Let's wrap up the meeting."),
]

공무원_단어 = [
    ("abate", "줄이다, 약화시키다", "The storm finally abated."),
    ("abdicate", "퇴위하다", "The king abdicated the throne."),
    ("aberration", "일탈, 이상", "This behavior is an aberration."),
    ("abhor", "혐오하다", "I abhor any form of violence."),
    ("abrogate", "폐지하다", "The treaty was abrogated last year."),
    ("abstain", "삼가다", "She abstains from alcohol."),
    ("acquiesce", "묵인하다", "He acquiesced to their demands."),
    ("acrimonious", "신랄한", "The divorce was acrimonious."),
    ("adamant", "완강한", "She was adamant about going."),
    ("admonish", "훈계하다", "The judge admonished the defendant."),
    ("adversary", "적", "He defeated his adversary in court."),
    ("alleviate", "완화하다", "This medicine alleviates pain."),
    ("amalgamate", "합병하다", "The two firms amalgamated."),
    ("ameliorate", "개선하다", "Reforms aim to ameliorate conditions."),
    ("anomaly", "변칙", "The data shows an anomaly."),
    ("antipathy", "반감", "He has an antipathy toward bureaucracy."),
    ("apathy", "무관심", "Voter apathy is a serious issue."),
    ("arduous", "힘든", "The journey was arduous."),
    ("articulate", "분명히 말하다", "She articulates her views well."),
    ("ascertain", "확인하다", "We must ascertain the facts first."),
    ("assiduous", "근면한", "He is an assiduous student."),
    ("astute", "영민한", "She is an astute investor."),
    ("augment", "늘리다", "We will augment the budget."),
    ("austere", "엄격한, 검소한", "He lived an austere life."),
    ("autonomous", "자치의", "The region is autonomous."),
    ("belligerent", "적대적인", "His tone was belligerent."),
    ("benevolent", "자비로운", "A benevolent donor funded the school."),
    ("brevity", "간결함", "I appreciate your brevity."),
    ("cajole", "회유하다", "She cajoled him into helping."),
    ("candor", "솔직함", "I admire her candor."),
    ("capricious", "변덕스러운", "The weather is capricious here."),
    ("censure", "비난하다", "Officials censured the policy."),
    ("circumvent", "우회하다", "He tried to circumvent the rules."),
    ("clandestine", "비밀의", "They held clandestine meetings."),
    ("coerce", "강요하다", "No one can coerce me into lying."),
    ("cogent", "설득력 있는", "She made a cogent argument."),
    ("complacent", "자만하는", "Don't become complacent after success."),
    ("concede", "인정하다", "He conceded defeat."),
    ("conciliatory", "화해적인", "He took a conciliatory tone."),
    ("condone", "묵인하다", "We cannot condone such behavior."),
    ("confound", "당황시키다", "The results confounded scientists."),
    ("consummate", "완벽한", "She is a consummate professional."),
    ("contentious", "논쟁적인", "That is a contentious issue."),
    ("corroborate", "입증하다", "Witnesses corroborated his story."),
    ("credulous", "잘 믿는", "He is too credulous of strangers."),
    ("culpable", "유죄의", "The company was culpable for the spill."),
    ("cursory", "피상적인", "A cursory glance is not enough."),
    ("dearth", "부족", "There is a dearth of qualified workers."),
    ("debunk", "폭로하다", "The study debunks common myths."),
    ("delineate", "윤곽을 그리다", "The contract delineates duties."),
    ("deride", "조롱하다", "Critics derided his work."),
    ("desultory", "산만한", "He made desultory remarks."),
    ("dichotomy", "이분법", "The dichotomy is false."),
    ("disparate", "이질적인", "The data is from disparate sources."),
    ("disseminate", "퍼뜨리다", "We disseminate information widely."),
    ("divulge", "누설하다", "He refused to divulge details."),
    ("dogmatic", "독단적인", "His dogmatic views are unwelcome."),
    ("ebullient", "활기찬", "She has an ebullient personality."),
    ("egregious", "엄청난", "That was an egregious mistake."),
    ("elicit", "끌어내다", "The question elicited a strong response."),
    ("eloquent", "웅변의", "He gave an eloquent speech."),
    ("emulate", "본받다", "Students should emulate good leaders."),
    ("enervate", "기력을 빼앗다", "The heat enervated us."),
    ("ephemeral", "일시적인", "Fame is often ephemeral."),
    ("equivocal", "모호한", "His answer was equivocal."),
    ("eradicate", "근절하다", "We aim to eradicate poverty."),
    ("erudite", "박학한", "He is an erudite scholar."),
    ("esoteric", "난해한", "The lecture was too esoteric."),
    ("exacerbate", "악화시키다", "Stress can exacerbate illness."),
    ("exonerate", "무죄임을 입증하다", "New evidence exonerated him."),
    ("expedient", "편의적인", "It was the most expedient solution."),
    ("extol", "격찬하다", "Critics extolled the novel."),
    ("fastidious", "까다로운", "He is fastidious about details."),
    ("fortuitous", "우연한", "It was a fortuitous meeting."),
    ("garrulous", "수다스러운", "The garrulous host wouldn't stop talking."),
    ("gregarious", "사교적인", "She is a gregarious woman."),
    ("hackneyed", "진부한", "That phrase is hackneyed."),
    ("impervious", "영향받지 않는", "He is impervious to criticism."),
    ("impetuous", "충동적인", "Don't make impetuous decisions."),
    ("inadvertent", "부주의한", "It was an inadvertent error."),
    ("incessant", "끊임없는", "The incessant noise was annoying."),
    ("inculcate", "주입시키다", "We inculcate good values in children."),
    ("indolent", "게으른", "He has become indolent."),
    ("ineffable", "형언할 수 없는", "The view was ineffable."),
    ("inveterate", "상습적인", "He is an inveterate gambler."),
    ("juxtapose", "병치하다", "The artist juxtaposes light and shadow."),
    ("laconic", "말수가 적은", "His laconic reply surprised me."),
    ("lassitude", "무기력", "A feeling of lassitude swept over her."),
    ("magnanimous", "관대한", "The winner was magnanimous in victory."),
    ("malign", "비방하다", "He maligned his rivals openly."),
    ("mitigate", "완화하다", "Steps were taken to mitigate damage."),
    ("obfuscate", "모호하게 하다", "He tried to obfuscate the truth."),
    ("obstinate", "완고한", "She is obstinate in her opinions."),
    ("ostentatious", "과시적인", "His lifestyle is ostentatious."),
    ("perfunctory", "형식적인", "He gave a perfunctory nod."),
    ("propitious", "좋은 조건의", "This is a propitious time to invest."),
    ("recalcitrant", "반항적인", "The recalcitrant student was suspended."),
    ("tacit", "암묵적인", "We had a tacit agreement."),
    ("ubiquitous", "어디에나 있는", "Smartphones are ubiquitous now."),
    ("vindicate", "정당함을 입증하다", "Time will vindicate his decision."),
]

공무원_숙어 = [
    ("abide by", "준수하다", "We must abide by the law."),
    ("account for", "설명하다", "The minister must account for the policy."),
    ("adhere to", "고수하다", "Adhere to the regulations strictly."),
    ("amount to", "~에 달하다", "Damages amount to millions."),
    ("at the expense of", "~을 희생하여", "Growth at the expense of environment is unwise."),
    ("at the mercy of", "~의 처분에 맡겨진", "Citizens are at the mercy of policy changes."),
    ("be averse to", "싫어하다", "He is averse to taking risks."),
    ("be conducive to", "~에 도움이 되다", "This climate is conducive to learning."),
    ("be obliged to", "~할 의무가 있다", "Officials are obliged to disclose assets."),
    ("be subject to", "~의 영향을 받다", "All laws are subject to revision."),
    ("bear in mind", "명심하다", "Bear in mind the consequences."),
    ("by virtue of", "~덕분에", "By virtue of his office, he chairs the meeting."),
    ("come to terms with", "받아들이다", "She came to terms with the loss."),
    ("comply with", "준수하다", "All firms must comply with the law."),
    ("dispense with", "없이 지내다", "We can dispense with formalities."),
    ("dwell on", "~에 대해 곱씹다", "Don't dwell on the past."),
    ("embark on", "착수하다", "He embarked on a new career."),
    ("fall short of", "미치지 못하다", "Results fell short of expectations."),
    ("for the sake of", "~을 위해", "For the sake of justice, we proceed."),
    ("give credence to", "신뢰하다", "I give credence to her testimony."),
    ("give rise to", "야기하다", "This policy will give rise to debate."),
    ("have a bearing on", "관련 있다", "This evidence has a bearing on the case."),
    ("in accordance with", "~에 따라", "In accordance with the rules."),
    ("in conjunction with", "~와 함께", "In conjunction with other agencies."),
    ("in lieu of", "~대신에", "Cash in lieu of vacation days."),
    ("in the wake of", "~의 여파로", "In the wake of the scandal."),
    ("lend itself to", "~에 적합하다", "The space lends itself to events."),
    ("live up to", "부응하다", "He failed to live up to his promise."),
    ("make allowance for", "감안하다", "Make allowance for delays."),
    ("make headway", "진척시키다", "We made headway on the bill."),
    ("on the verge of", "~의 직전에", "The country is on the verge of reform."),
    ("pave the way for", "길을 열다", "This paves the way for change."),
    ("pay heed to", "주의를 기울이다", "Pay heed to expert warnings."),
    ("play a role in", "역할을 하다", "Citizens play a role in democracy."),
    ("prevail over", "우세하다", "Justice will prevail over corruption."),
    ("put forward", "제시하다", "The minister put forward a proposal."),
    ("rest on", "~에 달려 있다", "Success rests on cooperation."),
    ("shed light on", "밝히다", "The report shed light on the issue."),
    ("stem from", "~에서 비롯되다", "Conflict stems from inequality."),
    ("subject to", "~을 조건으로", "Subject to approval by the board."),
    ("take exception to", "이의를 제기하다", "I take exception to that claim."),
    ("take into account", "고려하다", "Take into account public opinion."),
    ("take issue with", "이의를 제기하다", "I take issue with that point."),
    ("take precedence over", "우선하다", "Safety takes precedence over speed."),
    ("to the detriment of", "~에 손해를 끼치며", "Profits at the detriment of welfare."),
    ("tantamount to", "~에 해당하는", "This is tantamount to fraud."),
    ("with regard to", "~에 관하여", "With regard to your request."),
    ("with the exception of", "~을 제외하고", "With the exception of holidays."),
    ("without prejudice", "권리 침해 없이", "Settled without prejudice."),
    ("yield to", "굴복하다", "The government yielded to pressure."),
]

내신_단어 = [
    ("ability", "능력", "She has the ability to learn quickly."),
    ("accept", "받아들이다", "I accept your apology."),
    ("achieve", "성취하다", "You can achieve your dreams."),
    ("activity", "활동", "Sports is my favorite activity."),
    ("add", "더하다", "Add some sugar to the tea."),
    ("afraid", "두려워하는", "Don't be afraid of the dark."),
    ("agree", "동의하다", "I agree with you."),
    ("allow", "허락하다", "My parents allow me to stay out."),
    ("answer", "답하다", "Please answer the question."),
    ("appear", "나타나다", "A rainbow appeared after the rain."),
    ("believe", "믿다", "I believe in you."),
    ("borrow", "빌리다", "Can I borrow your pen?"),
    ("break", "부수다", "Don't break the window."),
    ("bring", "가져오다", "Please bring your textbook."),
    ("busy", "바쁜", "I am busy this weekend."),
    ("careful", "조심하는", "Be careful crossing the street."),
    ("catch", "잡다", "Catch the ball!"),
    ("cause", "원인", "What is the cause of the problem?"),
    ("change", "바꾸다", "I want to change my clothes."),
    ("choose", "선택하다", "Choose your favorite color."),
    ("clean", "깨끗한", "Keep your room clean."),
    ("clear", "명확한", "The instructions are clear."),
    ("close", "가까운", "The store is close to my house."),
    ("collect", "모으다", "I collect stamps."),
    ("compare", "비교하다", "Don't compare yourself to others."),
    ("complete", "완료하다", "Complete the assignment by Friday."),
    ("continue", "계속하다", "Please continue your story."),
    ("cool", "시원한", "The water is cool."),
    ("create", "만들다", "Artists create beautiful works."),
    ("cross", "건너다", "Cross the street carefully."),
    ("dangerous", "위험한", "Smoking is dangerous."),
    ("decide", "결정하다", "I can't decide what to wear."),
    ("delicious", "맛있는", "This pizza is delicious."),
    ("describe", "묘사하다", "Describe your hometown."),
    ("develop", "발전시키다", "Read books to develop your mind."),
    ("difficult", "어려운", "This question is difficult."),
    ("discover", "발견하다", "Scientists discover new things daily."),
    ("drop", "떨어뜨리다", "Don't drop the glass."),
    ("enjoy", "즐기다", "I enjoy reading books."),
    ("enough", "충분한", "We have enough food."),
    ("especially", "특히", "I love fruit, especially apples."),
    ("excited", "신난", "I am excited for the trip."),
    ("exercise", "운동", "Daily exercise is good for you."),
    ("experience", "경험", "I have no experience in cooking."),
    ("explain", "설명하다", "Can you explain this to me?"),
    ("famous", "유명한", "He is a famous singer."),
    ("feel", "느끼다", "I feel happy today."),
    ("finally", "마침내", "We finally arrived home."),
    ("follow", "따르다", "Follow the rules."),
    ("forget", "잊다", "Don't forget your umbrella."),
    ("friendly", "친절한", "She is very friendly."),
    ("future", "미래", "What do you want to do in the future?"),
    ("happen", "일어나다", "What happened yesterday?"),
    ("heavy", "무거운", "This box is too heavy."),
    ("helpful", "도움이 되는", "Your advice is helpful."),
    ("holiday", "휴일", "Tomorrow is a holiday."),
    ("hope", "희망하다", "I hope you feel better."),
    ("however", "그러나", "It rained; however, we went out."),
    ("important", "중요한", "Health is important."),
    ("interesting", "흥미로운", "This book is interesting."),
    ("introduce", "소개하다", "Let me introduce my friend."),
    ("invite", "초대하다", "I will invite you to my party."),
    ("join", "가입하다", "I joined the soccer club."),
    ("journey", "여행", "The journey was long."),
    ("judge", "판단하다", "Don't judge a book by its cover."),
    ("kind", "친절한", "She is a kind person."),
    ("learn", "배우다", "I learn English every day."),
    ("leave", "떠나다", "I leave for school at 8."),
    ("lend", "빌려주다", "Can you lend me a book?"),
    ("lonely", "외로운", "He felt lonely without friends."),
    ("lose", "잃다", "Don't lose your keys."),
    ("lucky", "운이 좋은", "You are lucky to have such friends."),
    ("memory", "기억", "I have a good memory."),
    ("mistake", "실수", "Everyone makes mistakes."),
    ("nervous", "긴장한", "I'm nervous about the test."),
    ("notice", "알아차리다", "I didn't notice the sign."),
    ("offer", "제안하다", "He offered me a job."),
    ("often", "자주", "I often go to the library."),
    ("opinion", "의견", "What's your opinion?"),
    ("peace", "평화", "We all want peace."),
    ("perhaps", "아마도", "Perhaps it will rain later."),
    ("plan", "계획", "What are your plans for tomorrow?"),
    ("popular", "인기 있는", "K-pop is popular worldwide."),
    ("practice", "연습하다", "Practice makes perfect."),
    ("prepare", "준비하다", "Prepare for the exam carefully."),
    ("present", "선물", "I got a present for my birthday."),
    ("probably", "아마도", "It will probably rain."),
    ("promise", "약속하다", "I promise to help you."),
    ("protect", "보호하다", "Parents protect their children."),
    ("proud", "자랑스러운", "I am proud of you."),
    ("receive", "받다", "I received a letter today."),
    ("remember", "기억하다", "Remember to lock the door."),
    ("respect", "존경하다", "I respect my teachers."),
    ("return", "돌아오다", "When will you return?"),
    ("several", "몇몇의", "I have several friends here."),
    ("share", "공유하다", "Share your toys with others."),
    ("solve", "해결하다", "Let's solve this problem together."),
    ("special", "특별한", "Today is a special day."),
    ("suggest", "제안하다", "I suggest we leave now."),
    ("wonderful", "멋진", "We had a wonderful time."),
]

내신_숙어 = [
    ("a lot of", "많은", "I have a lot of homework."),
    ("ask for", "요청하다", "Ask for help when needed."),
    ("at first", "처음에는", "At first, I was nervous."),
    ("at last", "마침내", "At last, the bus arrived."),
    ("at least", "적어도", "Sleep at least 8 hours."),
    ("at the same time", "동시에", "We arrived at the same time."),
    ("be able to", "~할 수 있다", "I am able to swim."),
    ("be afraid of", "~을 두려워하다", "I am afraid of spiders."),
    ("be busy with", "~로 바쁘다", "She is busy with homework."),
    ("be famous for", "~로 유명하다", "Korea is famous for kimchi."),
    ("be filled with", "~로 가득 차다", "The box is filled with books."),
    ("be full of", "~로 가득하다", "The room is full of people."),
    ("be good at", "~을 잘하다", "He is good at math."),
    ("be interested in", "~에 흥미가 있다", "I am interested in music."),
    ("be late for", "~에 늦다", "Don't be late for class."),
    ("be made of", "~로 만들어지다", "The table is made of wood."),
    ("be proud of", "~을 자랑스러워하다", "I am proud of my family."),
    ("be similar to", "~와 비슷하다", "Korean is similar to Japanese."),
    ("by the way", "그런데", "By the way, where are you going?"),
    ("each other", "서로", "We help each other."),
    ("for example", "예를 들어", "Many fruits, for example, apples."),
    ("for the first time", "처음으로", "I tried sushi for the first time."),
    ("get off", "내리다", "Get off at the next stop."),
    ("get on", "타다", "Get on the bus quickly."),
    ("get up", "일어나다", "I get up at 7 every day."),
    ("give up", "포기하다", "Never give up your dreams."),
    ("go on", "계속하다", "Please go on with your story."),
    ("go out", "외출하다", "Let's go out for dinner."),
    ("grow up", "자라다", "I grew up in Seoul."),
    ("have to", "~해야 한다", "I have to study tonight."),
    ("how about", "~는 어때?", "How about pizza?"),
    ("in front of", "~앞에", "Stand in front of the door."),
    ("in the end", "결국", "In the end, we won the game."),
    ("listen to", "~을 듣다", "I listen to music daily."),
    ("look after", "돌보다", "Please look after my dog."),
    ("look at", "~을 보다", "Look at this picture."),
    ("look for", "~을 찾다", "I'm looking for my keys."),
    ("look like", "~처럼 보이다", "You look like your father."),
    ("make friends", "친구를 사귀다", "It's easy to make friends here."),
    ("of course", "물론", "Of course you can join us."),
    ("once upon a time", "옛날 옛적에", "Once upon a time, there was a king."),
    ("pick up", "집어 들다", "Pick up your toys."),
    ("right away", "즉시", "Come here right away."),
    ("take a picture", "사진을 찍다", "Take a picture of us."),
    ("take a walk", "산책하다", "Let's take a walk in the park."),
    ("take care of", "돌보다", "Take care of yourself."),
    ("thanks to", "~덕분에", "Thanks to you, I passed."),
    ("throw away", "버리다", "Throw away the trash."),
    ("wait for", "기다리다", "I will wait for you."),
    ("would like to", "~하고 싶다", "I would like to go home."),
]

# Sanity check
assert len(수능_단어) == 100, len(수능_단어)
assert len(수능_숙어) == 50, len(수능_숙어)
assert len(토익_단어) == 100, len(토익_단어)
assert len(토익_숙어) == 50, len(토익_숙어)
assert len(공무원_단어) == 100, len(공무원_단어)
assert len(공무원_숙어) == 50, len(공무원_숙어)
assert len(내신_단어) == 100, len(내신_단어)
assert len(내신_숙어) == 50, len(내신_숙어)

# ============================================================
# BUILD WORKBOOK
# ============================================================

wb = Workbook()
wb.remove(wb.active)

EXAM_COLORS = {
    "수능": "1F6FEB",
    "토익": "2DA44E",
    "공무원": "BF8700",
    "내신": "8250DF",
}

THIN = Side(style="thin", color="DDDDDD")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

def add_sheet(title, color_hex, rows):
    ws = wb.create_sheet(title)
    ws.sheet_view.showGridLines = False

    # Header row
    headers = ["No.", "English", "Korean", "Example"]
    for col, h in enumerate(headers, start=1):
        c = ws.cell(row=1, column=col, value=h)
        c.font = Font(name="Arial", bold=True, color="FFFFFF", size=11)
        c.fill = PatternFill("solid", start_color=color_hex)
        c.alignment = Alignment(horizontal="center", vertical="center")
        c.border = BORDER

    # Data rows
    for i, (eng, kor, ex) in enumerate(rows, start=1):
        r = i + 1
        ws.cell(row=r, column=1, value=i).alignment = Alignment(horizontal="center", vertical="center")
        ws.cell(row=r, column=2, value=eng).font = Font(name="Arial", bold=True, size=11)
        ws.cell(row=r, column=3, value=kor).font = Font(name="Arial", size=11)
        ws.cell(row=r, column=4, value=ex).font = Font(name="Arial", italic=True, color="555555", size=11)
        for col in range(1, 5):
            cell = ws.cell(row=r, column=col)
            cell.border = BORDER
            if col >= 2:
                cell.alignment = Alignment(horizontal="left", vertical="center", wrap_text=True)
        # Alternate row shading
        if i % 2 == 0:
            for col in range(1, 5):
                ws.cell(row=r, column=col).fill = PatternFill("solid", start_color="F6F8FA")

    # Column widths
    ws.column_dimensions["A"].width = 5
    ws.column_dimensions["B"].width = 22
    ws.column_dimensions["C"].width = 26
    ws.column_dimensions["D"].width = 58

    ws.row_dimensions[1].height = 24
    ws.freeze_panes = "A2"

# Index sheet
idx = wb.create_sheet("목차")
idx.sheet_view.showGridLines = False
idx["A1"] = "시험별 어휘 정리"
idx["A1"].font = Font(name="Arial", bold=True, size=18)
idx.merge_cells("A1:C1")
idx.row_dimensions[1].height = 32

idx["A3"] = "시험"
idx["B3"] = "단어 (100개)"
idx["C3"] = "숙어 (50개)"
for col_letter in ["A", "B", "C"]:
    c = idx[f"{col_letter}3"]
    c.font = Font(name="Arial", bold=True, color="FFFFFF", size=11)
    c.fill = PatternFill("solid", start_color="24292F")
    c.alignment = Alignment(horizontal="center", vertical="center")
    c.border = BORDER

idx_rows = [
    ("수능", "수능 단어", "수능 숙어"),
    ("토익", "토익 단어", "토익 숙어"),
    ("공무원", "공무원 단어", "공무원 숙어"),
    ("내신", "내신 단어", "내신 숙어"),
]
for i, (exam, w, p) in enumerate(idx_rows, start=4):
    color = EXAM_COLORS[exam]
    cell_a = idx.cell(row=i, column=1, value=exam)
    cell_a.font = Font(name="Arial", bold=True, color="FFFFFF", size=11)
    cell_a.fill = PatternFill("solid", start_color=color)
    cell_a.alignment = Alignment(horizontal="center", vertical="center")
    cell_a.border = BORDER

    for col, sheet_name in [(2, w), (3, p)]:
        c = idx.cell(row=i, column=col, value=sheet_name)
        c.hyperlink = f"#'{sheet_name}'!A1"
        c.font = Font(name="Arial", color="0969DA", underline="single", size=11)
        c.alignment = Alignment(horizontal="center", vertical="center")
        c.border = BORDER
    idx.row_dimensions[i].height = 22

idx.column_dimensions["A"].width = 14
idx.column_dimensions["B"].width = 22
idx.column_dimensions["C"].width = 22

idx["A9"] = "총 단어 400개 + 숙어 200개 = 600 항목"
idx["A9"].font = Font(name="Arial", italic=True, color="666666", size=10)
idx.merge_cells("A9:C9")

# Add exam sheets
sheets_spec = [
    ("수능 단어", "수능", 수능_단어),
    ("수능 숙어", "수능", 수능_숙어),
    ("토익 단어", "토익", 토익_단어),
    ("토익 숙어", "토익", 토익_숙어),
    ("공무원 단어", "공무원", 공무원_단어),
    ("공무원 숙어", "공무원", 공무원_숙어),
    ("내신 단어", "내신", 내신_단어),
    ("내신 숙어", "내신", 내신_숙어),
]
for sheet_name, exam, rows in sheets_spec:
    add_sheet(sheet_name, EXAM_COLORS[exam], rows)

out = "/Users/pyunhanga/output/시험별_필수어휘_숙어.xlsx"
wb.save(out)
print(f"Saved: {out}")
print(f"Sheets: {wb.sheetnames}")
